140 get calendar data from cms
YoungVision-eV/website pull request #175
Opened 2024-05-16 11:48 UTC by Han2-Ro

2024-05-16 12:00 UTC, Han2-Ro commented
TODO: Info links lead to 404

2024-05-16 14:23 UTC, MrGreenTea requested changes

2024-05-16 14:23 UTC, MrGreenTea commented on src/data/events.ts
> +    `${process.env.CMS_URL}/api/events?sort=date&where[start][greater_than]=${today.toISOString()}&limit=3`,
Maybe use [`qs`](https://www.npmjs.com/package/qs) for these query strings for better readability?

2024-05-17 09:47 UTC, MrGreenTea approved these changes

2024-05-17 09:49 UTC, merged